<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RepositoryUrl>https://github.com/Robin-Goerlach/SASD-Editor-Toolkit</RepositoryUrl>
    <Authors>SASD-GmbH</Authors>
    <Company>SASD-GmbH</Company>
    <Copyright>Copyright (c) 2026 SASD-GmbH</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
