<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <IsPackable>false</IsPackable>
    <AssemblyName>Sasd.EditorToolkit.Sample.FirstEd.WinForms</AssemblyName>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Sasd.EditorToolkit.Core\Sasd.EditorToolkit.Core.csproj" />
    <ProjectReference Include="..\..\src\Sasd.EditorToolkit.WinForms\Sasd.EditorToolkit.WinForms.csproj" />
  </ItemGroup>
</Project>
